export const WORK_EDITORIAL = {
  luckyDay: {
    title: "Lucky Day",
    stage: "finished",
    description: "An interaction you can feel.",
    role: "Design + build",
    detail: "iOS · Motion and haptics study",
    href: "/projects/lucky-day",
    primaryImage: "/assets/work/lucky-day-hero.jpg",
    detailImage: "/assets/work/lucky-day-detail.jpg",
  },
  internship: {
    title: "Research internship",
    stage: "finished",
    description: "Making dense information easier to search and understand.",
    role: "Product design",
    detail: "Research + prototyping",
    image: "/assets/work/internship-research.jpg",
    detailImage: "/assets/work/internship-detail.jpg",
  },
  wylde: {
    title: "Wylde",
    stage: "making",
    description: "Less explaining. More playing.",
    role: "Design + build",
    detail: "iOS · Party card game",
    href: "/projects/wylde",
    image: "/assets/work/wylde-space.jpg",
    detailImage: "/assets/work/wylde-detail.jpg",
  },
  sachetana: {
    title: "Sachetana",
    stage: "finished",
    description: "A private space for students to check in with themselves.",
    role: "Design + build",
    detail: "Student wellness · iOS & web",
    href: "/projects/sachetana",
    image: "/assets/work/sachetana-wellness.jpg",
    detailImage: "/assets/work/sachetana-detail.jpg",
  },
} as const;
