// Generated by scripts/build-opening-assets.py. Pixel positions inside the cropped window art.
export const OPENING_GEOMETRY = {
  "window": {
    "w": 960,
    "h": 1434
  },
  "shutterLeft": {
    "x": 152,
    "y": 544,
    "w": 332,
    "h": 791
  },
  "shutterRight": {
    "x": 480,
    "y": 535,
    "w": 330,
    "h": 803
  },
  "panel": {
    "x": 151,
    "y": 534,
    "w": 660,
    "h": 805
  },
  "panelInk": "#1e2e5a"
} as const;
